export const news = [
    {
        id: 1,
        image_url: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2021-11/211118-apple-tim-cook-se-202p-eb76fa.jpg',
        title: 'Apple posts internal memo affirming employees right to discuss pay',
        description: 'Following months of internal controversy about how much workers make at one of the highest valued companies in the world, Apple has announced that employees have the right to discuss working conditions and pay, according to a staff memo obtained by NBC News. Since 2016, Apple has said its workers in the United States receive equal pay for equal work. But it quietly shut down attempts by workers to validate this claim, according to two current and former employees. Now, according to the memo, Apple is telling staff they have the right to discuss their wages and air their concerns externally, a major shift for the famously secretive tech giant. The note was posted on Apple’s internal people site, to which the company’s 80,000 hourly and salaried employees in the U.S. have access.“Our policies do not restrict employees from speaking freely about their wages, hours, or working conditions,” the memo reads. “We encourage any employee with concerns to raise them in the way they feel most comfortable, internally or externally, including through their manager, any Apple manager, People Support, People Business Partner, or Business Conduct.Apple did not immediately respond to a request for comment from NBC News.The language affirms a right given to private sector employees under the National Labor Relations Act, which allows workers to organize and discuss their hours and wages.The memo echoes language in Apple’s business conduct policy, which says that nothing in the rule “should be interpreted as being restrictive of your right to speak freely about your wages, hours, or working conditions.”Apple declined to add similar language to its employment agreements when asked by a group of activists and shareholders earlier this year. The company said the language was already covered by its business conduct policy, according to the tech activist Ifeoma Ozoma. The memo is a win for Apple organizers like Cher Scarlett, who said in a National Labor Relations Board charge that the company has restricted their ability to discuss pay and working conditions by shutting down informal pay surveys and blocking a pay equity Slack channel.Since August, there have been eight unfair labor practices charges filed against Apple on issues ranging from unlawful discharge to harassment. One of these charges has been dismissed.',
        author: 'By Zoe Schiffer',
        date_create: '12 04 2022'
    },
    {
        id: 2,
        image_url: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2021-11/211117-iphone13-al-1122-2c4214.jpg',
        title: 'Apple posts internal memo affirming employees right to discuss pay',
        description: 'Following months of internal controversy about how much workers make at one of the highest valued companies in the world, Apple has announced that employees have the right to discuss working conditions and pay, according to a staff memo obtained by NBC News. Since 2016, Apple has said its workers in the United States receive equal pay for equal work. But it quietly shut down attempts by workers to validate this claim, according to two current and former employees. Now, according to the memo, Apple is telling staff they have the right to discuss their wages and air their concerns externally, a major shift for the famously secretive tech giant. The note was posted on Apple’s internal people site, to which the company’s 80,000 hourly and salaried employees in the U.S. have access.“Our policies do not restrict employees from speaking freely about their wages, hours, or working conditions,” the memo reads. “We encourage any employee with concerns to raise them in the way they feel most comfortable, internally or externally, including through their manager, any Apple manager, People Support, People Business Partner, or Business Conduct.Apple did not immediately respond to a request for comment from NBC News.The language affirms a right given to private sector employees under the National Labor Relations Act, which allows workers to organize and discuss their hours and wages.The memo echoes language in Apple’s business conduct policy, which says that nothing in the rule “should be interpreted as being restrictive of your right to speak freely about your wages, hours, or working conditions.”Apple declined to add similar language to its employment agreements when asked by a group of activists and shareholders earlier this year. The company said the language was already covered by its business conduct policy, according to the tech activist Ifeoma Ozoma. The memo is a win for Apple organizers like Cher Scarlett, who said in a National Labor Relations Board charge that the company has restricted their ability to discuss pay and working conditions by shutting down informal pay surveys and blocking a pay equity Slack channel.Since August, there have been eight unfair labor practices charges filed against Apple on issues ranging from unlawful discharge to harassment. One of these charges has been dismissed.',
        author: 'By Zoe Schiffer',
        date_create: '12 04 2022'
    },
    {
        id: 3,
        image_url: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2022-01/220103-tim-cook-ew-156p-6e0376.jpg',
        title: 'Apple posts internal memo affirming employees right to discuss pay',
        description: 'Following months of internal controversy about how much workers make at one of the highest valued companies in the world, Apple has announced that employees have the right to discuss working conditions and pay, according to a staff memo obtained by NBC News. Since 2016, Apple has said its workers in the United States receive equal pay for equal work. But it quietly shut down attempts by workers to validate this claim, according to two current and former employees. Now, according to the memo, Apple is telling staff they have the right to discuss their wages and air their concerns externally, a major shift for the famously secretive tech giant. The note was posted on Apple’s internal people site, to which the company’s 80,000 hourly and salaried employees in the U.S. have access.“Our policies do not restrict employees from speaking freely about their wages, hours, or working conditions,” the memo reads. “We encourage any employee with concerns to raise them in the way they feel most comfortable, internally or externally, including through their manager, any Apple manager, People Support, People Business Partner, or Business Conduct.Apple did not immediately respond to a request for comment from NBC News.The language affirms a right given to private sector employees under the National Labor Relations Act, which allows workers to organize and discuss their hours and wages.The memo echoes language in Apple’s business conduct policy, which says that nothing in the rule “should be interpreted as being restrictive of your right to speak freely about your wages, hours, or working conditions.”Apple declined to add similar language to its employment agreements when asked by a group of activists and shareholders earlier this year. The company said the language was already covered by its business conduct policy, according to the tech activist Ifeoma Ozoma. The memo is a win for Apple organizers like Cher Scarlett, who said in a National Labor Relations Board charge that the company has restricted their ability to discuss pay and working conditions by shutting down informal pay surveys and blocking a pay equity Slack channel.Since August, there have been eight unfair labor practices charges filed against Apple on issues ranging from unlawful discharge to harassment. One of these charges has been dismissed.',
        author: 'By Zoe Schiffer',
        date_create: '12 04 2022'
    },
    {
        id: 4,
        image_url: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2021-12/211208-apple-store-al-0737-4f4c31.jpg',
        title: 'Apple store in Texas closes in Covid outbreak',
        description: 'Following months of internal controversy about how much workers make at one of the highest valued companies in the world, Apple has announced that employees have the right to discuss working conditions and pay, according to a staff memo obtained by NBC News. Since 2016, Apple has said its workers in the United States receive equal pay for equal work. But it quietly shut down attempts by workers to validate this claim, according to two current and former employees. Now, according to the memo, Apple is telling staff they have the right to discuss their wages and air their concerns externally, a major shift for the famously secretive tech giant. The note was posted on Apple’s internal people site, to which the company’s 80,000 hourly and salaried employees in the U.S. have access.“Our policies do not restrict employees from speaking freely about their wages, hours, or working conditions,” the memo reads. “We encourage any employee with concerns to raise them in the way they feel most comfortable, internally or externally, including through their manager, any Apple manager, People Support, People Business Partner, or Business Conduct.Apple did not immediately respond to a request for comment from NBC News.The language affirms a right given to private sector employees under the National Labor Relations Act, which allows workers to organize and discuss their hours and wages.The memo echoes language in Apple’s business conduct policy, which says that nothing in the rule “should be interpreted as being restrictive of your right to speak freely about your wages, hours, or working conditions.”Apple declined to add similar language to its employment agreements when asked by a group of activists and shareholders earlier this year. The company said the language was already covered by its business conduct policy, according to the tech activist Ifeoma Ozoma. The memo is a win for Apple organizers like Cher Scarlett, who said in a National Labor Relations Board charge that the company has restricted their ability to discuss pay and working conditions by shutting down informal pay surveys and blocking a pay equity Slack channel.Since August, there have been eight unfair labor practices charges filed against Apple on issues ranging from unlawful discharge to harassment. One of these charges has been dismissed.',
        author: 'By Zoe Schiffer',
        date_create: '12 04 2022'
    },
    {
        id: 5,
        image_url: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/streams/2013/April/130404/1C6780139-tdy_rossen_phone_130220.jpg',
        title: 'Apple picking thieves snatch iPhones',
        description: 'Following months of internal controversy about how much workers make at one of the highest valued companies in the world, Apple has announced that employees have the right to discuss working conditions and pay, according to a staff memo obtained by NBC News. Since 2016, Apple has said its workers in the United States receive equal pay for equal work. But it quietly shut down attempts by workers to validate this claim, according to two current and former employees. Now, according to the memo, Apple is telling staff they have the right to discuss their wages and air their concerns externally, a major shift for the famously secretive tech giant. The note was posted on Apple’s internal people site, to which the company’s 80,000 hourly and salaried employees in the U.S. have access.“Our policies do not restrict employees from speaking freely about their wages, hours, or working conditions,” the memo reads. “We encourage any employee with concerns to raise them in the way they feel most comfortable, internally or externally, including through their manager, any Apple manager, People Support, People Business Partner, or Business Conduct.Apple did not immediately respond to a request for comment from NBC News.The language affirms a right given to private sector employees under the National Labor Relations Act, which allows workers to organize and discuss their hours and wages.The memo echoes language in Apple’s business conduct policy, which says that nothing in the rule “should be interpreted as being restrictive of your right to speak freely about your wages, hours, or working conditions.”Apple declined to add similar language to its employment agreements when asked by a group of activists and shareholders earlier this year. The company said the language was already covered by its business conduct policy, according to the tech activist Ifeoma Ozoma. The memo is a win for Apple organizers like Cher Scarlett, who said in a National Labor Relations Board charge that the company has restricted their ability to discuss pay and working conditions by shutting down informal pay surveys and blocking a pay equity Slack channel.Since August, there have been eight unfair labor practices charges filed against Apple on issues ranging from unlawful discharge to harassment. One of these charges has been dismissed.',
        author: 'By Zoe Schiffer',
        date_create: '12 04 2022'
    },
    {
        id: 6,
        image_url: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/newscms/2021_47/3521596/211127-bf-apple-deals-refresh-vl-2x1.jpg',
        title: 'Apple Black Friday deals still available on AirPods Pro, Apple Watches and more',
        description: 'Following months of internal controversy about how much workers make at one of the highest valued companies in the world, Apple has announced that employees have the right to discuss working conditions and pay, according to a staff memo obtained by NBC News. Since 2016, Apple has said its workers in the United States receive equal pay for equal work. But it quietly shut down attempts by workers to validate this claim, according to two current and former employees. Now, according to the memo, Apple is telling staff they have the right to discuss their wages and air their concerns externally, a major shift for the famously secretive tech giant. The note was posted on Apple’s internal people site, to which the company’s 80,000 hourly and salaried employees in the U.S. have access.“Our policies do not restrict employees from speaking freely about their wages, hours, or working conditions,” the memo reads. “We encourage any employee with concerns to raise them in the way they feel most comfortable, internally or externally, including through their manager, any Apple manager, People Support, People Business Partner, or Business Conduct.Apple did not immediately respond to a request for comment from NBC News.The language affirms a right given to private sector employees under the National Labor Relations Act, which allows workers to organize and discuss their hours and wages.The memo echoes language in Apple’s business conduct policy, which says that nothing in the rule “should be interpreted as being restrictive of your right to speak freely about your wages, hours, or working conditions.”Apple declined to add similar language to its employment agreements when asked by a group of activists and shareholders earlier this year. The company said the language was already covered by its business conduct policy, according to the tech activist Ifeoma Ozoma. The memo is a win for Apple organizers like Cher Scarlett, who said in a National Labor Relations Board charge that the company has restricted their ability to discuss pay and working conditions by shutting down informal pay surveys and blocking a pay equity Slack channel.Since August, there have been eight unfair labor practices charges filed against Apple on issues ranging from unlawful discharge to harassment. One of these charges has been dismissed.',
        author: 'By Zoe Schiffer',
        date_create: '12 04 2022'
    },
    {
        id: 7,
        image_url: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/newscms/2021_47/3521596/211127-bf-apple-deals-refresh-vl-2x1.jpg',
        title: 'Apple Black Friday deals still available on AirPods Pro, Apple Watches and more',
        description: 'Following months of internal controversy about how much workers make at one of the highest valued companies in the world, Apple has announced that employees have the right to discuss working conditions and pay, according to a staff memo obtained by NBC News. Since 2016, Apple has said its workers in the United States receive equal pay for equal work. But it quietly shut down attempts by workers to validate this claim, according to two current and former employees. Now, according to the memo, Apple is telling staff they have the right to discuss their wages and air their concerns externally, a major shift for the famously secretive tech giant. The note was posted on Apple’s internal people site, to which the company’s 80,000 hourly and salaried employees in the U.S. have access.“Our policies do not restrict employees from speaking freely about their wages, hours, or working conditions,” the memo reads. “We encourage any employee with concerns to raise them in the way they feel most comfortable, internally or externally, including through their manager, any Apple manager, People Support, People Business Partner, or Business Conduct.Apple did not immediately respond to a request for comment from NBC News.The language affirms a right given to private sector employees under the National Labor Relations Act, which allows workers to organize and discuss their hours and wages.The memo echoes language in Apple’s business conduct policy, which says that nothing in the rule “should be interpreted as being restrictive of your right to speak freely about your wages, hours, or working conditions.”Apple declined to add similar language to its employment agreements when asked by a group of activists and shareholders earlier this year. The company said the language was already covered by its business conduct policy, according to the tech activist Ifeoma Ozoma. The memo is a win for Apple organizers like Cher Scarlett, who said in a National Labor Relations Board charge that the company has restricted their ability to discuss pay and working conditions by shutting down informal pay surveys and blocking a pay equity Slack channel.Since August, there have been eight unfair labor practices charges filed against Apple on issues ranging from unlawful discharge to harassment. One of these charges has been dismissed.',
        author: 'By Zoe Schiffer',
        date_create: '12 04 2022'
    },
    {
        id: 8,
        image_url: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/newscms/2021_47/3521596/211127-bf-apple-deals-refresh-vl-2x1.jpg',
        title: 'Apple Black Friday deals still available on AirPods Pro, Apple Watches and more',
        description: 'Following months of internal controversy about how much workers make at one of the highest valued companies in the world, Apple has announced that employees have the right to discuss working conditions and pay, according to a staff memo obtained by NBC News. Since 2016, Apple has said its workers in the United States receive equal pay for equal work. But it quietly shut down attempts by workers to validate this claim, according to two current and former employees. Now, according to the memo, Apple is telling staff they have the right to discuss their wages and air their concerns externally, a major shift for the famously secretive tech giant. The note was posted on Apple’s internal people site, to which the company’s 80,000 hourly and salaried employees in the U.S. have access.“Our policies do not restrict employees from speaking freely about their wages, hours, or working conditions,” the memo reads. “We encourage any employee with concerns to raise them in the way they feel most comfortable, internally or externally, including through their manager, any Apple manager, People Support, People Business Partner, or Business Conduct.Apple did not immediately respond to a request for comment from NBC News.The language affirms a right given to private sector employees under the National Labor Relations Act, which allows workers to organize and discuss their hours and wages.The memo echoes language in Apple’s business conduct policy, which says that nothing in the rule “should be interpreted as being restrictive of your right to speak freely about your wages, hours, or working conditions.”Apple declined to add similar language to its employment agreements when asked by a group of activists and shareholders earlier this year. The company said the language was already covered by its business conduct policy, according to the tech activist Ifeoma Ozoma. The memo is a win for Apple organizers like Cher Scarlett, who said in a National Labor Relations Board charge that the company has restricted their ability to discuss pay and working conditions by shutting down informal pay surveys and blocking a pay equity Slack channel.Since August, there have been eight unfair labor practices charges filed against Apple on issues ranging from unlawful discharge to harassment. One of these charges has been dismissed.',
        author: 'By Zoe Schiffer',
        date_create: '12 04 2022'
    }
]